project_id = "zsmkhndwoxhwasrlzeox"

[functions.strava_callback]
verify_jwt = false

[functions.strava_webhook]
verify_jwt = false

[functions.cleanup_fitness_videos]
verify_jwt = false

[functions.validate_invitation]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true